spring:
  profiles:
    active: smart
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:postgresql://localhost:5432/hr
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    open-in-view: false

hr:
  raise:
    def:
      percent: 5
    smart:
      limits:
        20.0: 15
        10.0: 10
        5.0: 5
        2.5: 2
        1.0: 1

server:
  error:
    include-message: always