spring:
  profiles:
    active: smart
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:postgresql://localhost:5432/hr
    username: user
    password: userpass
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

hr:
  raise:
    def:
      percent: 5
    smart:
      limits:
        20.0: 15
        10.0: 10
        5.0: 5
        2.5: 2
        1.0: 1

server:
  error:
    include-message: always